# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0004_auto_20170914_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hs_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='fr', help_text='Private or Public High School', max_length=2),
        ),
    ]
