# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0006_auto_20170927_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
