# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0007_auto_20170927_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hs_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Public', 'Public')], default='fr', help_text='Private or Public High School', max_length=10),
        ),
    ]
