# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0008_auto_20170927_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='roster_website',
            field=models.URLField(null=True),
        ),
    ]
