# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rosters', '0010_auto_20171005_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_report', models.TextField(max_length=1000)),
                ('player_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosters.Player')),
                ('user_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_flag_player', 'Flag player roster data.'),),
            },
        ),
    ]
