# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0012_auto_20171103_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['school', 'number'], 'permissions': (('can_change_player', 'Can change player'),)},
        ),
    ]
