# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0014_auto_20171103_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.CharField(blank=True, choices=[('RedShirt', 'RedShirt'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='fr', help_text='Player Class Standing', max_length=20),
        ),
    ]
